### ISSUE TITLE
밭등록 작업내역 커밋후 풀 에러

### ISSUE THREAD

**Issue by sangkyoung0122** [sangkyoung0122/batassugi#10]
이슈제목 : 밭등록 작업내역 커밋후 풀 에러
이슈내용 : 밭등록 작업 후 커밋완료하여 Pull진행하였는데 DIRTY_WORKTREE 에러발생
이슈날짜:2018.05.17

**Comment by zzagam** [comment]
.gitignore 파일이 src 내부에 존재하여서 생긴 에러였으며 
src 내부에 존재하는 .gitignore 파일 삭제로 해결
