### ISSUE TITLE
회원정보 수정 패스워드, 패스워드 확인 불일치 등록가능

### ISSUE THREAD

**Issue by zzagam** [sangkyoung0122/batassugi#14]
회원정보 수정 패스워드, 패스워드 확인 불일치 등록가능

회원정보 수정에서 패스워드와 패스워드 확인이 불일치되어도 무조건 등록이 가능합니다.
2018-05-21

**Comment by jieun1127** [comment]
myinfoview.jsp의 script를 변경하였습니다.
