### ISSUE TITLE
회원가입, 회원정보수정 시 파일업로드 : 이미지파일이 아니어도 등록 및 수정 가능

### ISSUE THREAD

**Issue by zzagam** [sangkyoung0122/batassugi#15]
회원가입, 회원정보수정 시 파일업로드 : 이미지파일이 아니어도 등록 및 수정 가능

회원가입과 회원정보 수정 시 파일을 업로드 할 때 이미지 파일이 아니어도
등록이 되는 경우입니다. 이 경우, 거래게시판에 파일 업로드쪽을 참고하면 해결 가능할 것 같습니다.
2018-05-21

**Comment by jieun1127** [comment]
이미지파일만 올릴 수 있도록 설정하였습니다.
