### ISSUE TITLE
농지등록할때 현재날자보다 이전날짜로 입력이 할 수 있는 문제

### ISSUE THREAD

**Issue by ukyi** [sangkyoung0122/batassugi#16]
농지등록할때 현재날짜보다 이전날짜로 입력을 하고, 모집등록을 하게되면 대여기간이 -로 되는 문제

**Comment by zzagam** [comment]
날짜 비교하는 javascript 추가로 front에서 예외처리 완료. 추후에 backend에서 함께 예외처리하는 것으로 수정해야 합니다.
