### ISSUE TITLE
농지등록에서 작물 선택안하고 등록시 500에러 발생

### ISSUE THREAD

**Issue by ukyi** [sangkyoung0122/batassugi#17]
농지등록에서 작물을 선택안하고 등록하게되면 NullPointerException이 발생하여 서버500에러가 발생함

**Comment by zzagam** [comment]
front에서 onsubmit function 제어를 통해 예외처리 완료. 
추후 back에서까지 동시에 검사하는 단단한 프로그래밍 필요.
