### ISSUE TITLE
모집등록시 구매자가 대여신청했을때 평수 문제

### ISSUE THREAD

**Issue by ukyi** [sangkyoung0122/batassugi#18]
판매자가 5만평을 대여모집을 등록하고, 구매자가 대여신청을 5천평을 대여하게되면
판매자의 모집등록 가능한 평수가 4만5천평이 남아야하는데 -5천이 되버리는 현상.

**Comment by zzagam** [comment]
쿼리 조건분에 현재 남아있는 농지의 양 계산 중 rent_status가 '대기'이거나 '승인' 인 상태의 신청량을 빼는 것으로 해결.
