### ISSUE TITLE
거래게시판 댓글 길이에따라 댓글 위치가 달라지는 현상

### ISSUE THREAD

**Issue by jieun1127** [sangkyoung0122/batassugi#19]
거래게시판 댓글 길이에따라 댓글 위치가 달라지는 현상

거래게시판에서 작성한 댓글이 댓글 길이에 따라 위치가 달라짐.
2018-05-21

**Comment by mirpower10014** [comment]
<table> 구조였던 댓글 영역을 <div><label> 영역으로 변경하고 word-break: break-all; word-wrap: break-word;를 사용하여 게시판 테이블에 맞게 글씨 위치를 조절함
