### ISSUE TITLE
거래게시판에서 큰사진을 첨부할 경우, 미리보기 사이즈가 커지는 현상

### ISSUE THREAD

**Issue by jieun1127** [sangkyoung0122/batassugi#20]
거래게시판에서 큰사진을 첨부할 경우, 미리보기 사이즈가 커지는 현상

거래게시판 미리보기 사진크기를 고정해야함.
2018-05-21

**Comment by mirpower10014** [comment]
이미지에 width를 줘서 사진크기 고정완료
