### ISSUE TITLE
거래게시판에서 게시물에 댓글을 여러개 등록할 경우, 목록, 수정, 삭제 버튼이 보이지 않는 현상

### ISSUE THREAD

**Issue by jieun1127** [sangkyoung0122/batassugi#22]
거래게시판에서 게시물에 댓글을 여러개 등록할 경우, 목록, 수정, 삭제 버튼이 보이지 않는 현상

거래게시판에서 게시물에 댓글을 여러개 등록할 경우, 아래 메뉴들이 보이지 않음.
2018-05-21

**Comment by mirpower10014** [comment]
footer에 가려지는 문제로 영역에 빈 공간을 추가하여 해결
