### ISSUE TITLE
거래게시판에서 글 수정시, 원래 등록되어있던 사진이 사라지는 현상

### ISSUE THREAD

**Issue by jieun1127** [sangkyoung0122/batassugi#23]
거래게시판에서 글 수정시, 원래 등록되어있던 사진이 사라지는 현상

거래게시판에서 글 수정시, 원래 등록되어있던 사진이 보이지 않게됨.
2018-05-21

**Comment by mirpower10014** [comment]
게시글 수정 시 서비스에서 사진을 변경하면 그 사진을 저장하고 
변경하지 않으면 원래 등록되어어있더 사진을 불러오게 수정 완료
