### ISSUE TITLE
대여 게시판에서 신청 시 신청량 만큼 남아있는 대여가능량 업데이트 문제

### ISSUE THREAD

**Issue by zzagam** [sangkyoung0122/batassugi#25]
대여 게시판에서 신청 시 신청량 만큼 남아있는 대여가능량 업데이트 문제

대여 게시판에서 신청 시 판매자가 10000평을 오픈했고 대여자가 2000평을 신청하면 
남은 신청량 8000평이 나와야 하며, 
만약 10000평이 모두 신청되어 있는 상황이라면 신청게시판에 그 모집 글이 보이지 않아야 한다.
이것은 rent_status가 승인, 거절, 대기 세가지 상태로 구분되어 있고 승인이나 대기일 경우 그 양을 빼고
거절일 경우 그 양을 다시 recruit_size에 더해주면 될 듯 하다.
2018-05-22

**Comment by ukyi** [comment]
insert를 하고 update를 해서 문제 해결

대여신청 insert가 이루어 질때 바로 recruit_size를 신청한만큼 update를 해서 문제해결함.
insert,update 트랜잭션처리함.
