### ISSUE TITLE
대여 신청 게시판에서 모집을 등록한 밭 사진이 안나오는 문제

### ISSUE THREAD

**Issue by zzagam** [sangkyoung0122/batassugi#28]
대여 신청 게시판에서 모집을 등록한 밭 사진이 안나오는 문제

대여 신청 게시판에서 모집중인 농지의 사진이 나오지 않는 문제
2018-05-23

**Comment by mirpower10014** [comment]
rent.xml에 쿼리문 변경 및 view 변경
